import { DEFAULT_ELEMENT_STYLE, DEFAULT_TEXT_STYLE } from '@inkflow/elements';
import type { EditorState, StyleDefaults } from './types';

export const DEFAULT_STYLE: StyleDefaults = {
  strokeColor: DEFAULT_ELEMENT_STYLE.strokeColor,
  backgroundColor: DEFAULT_ELEMENT_STYLE.backgroundColor,
  fillStyle: DEFAULT_ELEMENT_STYLE.fillStyle,
  strokeWidth: DEFAULT_ELEMENT_STYLE.strokeWidth,
  strokeStyle: DEFAULT_ELEMENT_STYLE.strokeStyle,
  roughness: DEFAULT_ELEMENT_STYLE.roughness,
  opacity: DEFAULT_ELEMENT_STYLE.opacity,
  roundness: 'round',
  fontFamily: DEFAULT_TEXT_STYLE.fontFamily,
  fontSize: DEFAULT_TEXT_STYLE.fontSize,
  fontWeight: DEFAULT_TEXT_STYLE.fontWeight,
  fontStyle: DEFAULT_TEXT_STYLE.fontStyle,
  textDecoration: DEFAULT_TEXT_STYLE.textDecoration,
  textAlign: DEFAULT_TEXT_STYLE.textAlign,
  verticalAlign: 'middle',
  lineHeight: DEFAULT_TEXT_STYLE.lineHeight,
  letterSpacing: DEFAULT_TEXT_STYLE.letterSpacing,
  startArrowhead: 'none',
  endArrowhead: 'arrow',
  arrowPathStyle: 'sharp',
  connectorRouting: 'orthogonal',
  nodeShape: 'rounded-rectangle',
  polygonSides: 6,
  starSpikes: 5,
};

export function createInitialState(overrides: Partial<EditorState> = {}): EditorState {
  return {
    tool: 'selection',
    toolLocked: false,
    selectedIds: [],
    editingGroupId: null,
    hoveredId: null,
    textEdit: null,
    structuredEditId: null,
    cropId: null,
    viewport: { x: 0, y: 0, zoom: 1, width: 1, height: 1 },
    style: { ...DEFAULT_STYLE },
    grid: { visible: true, type: 'dot', size: 20 },
    snapping: { toGrid: false, toObjects: true, angle: true },
    theme: 'light',
    viewBackgroundColor: '#ffffff',
    readOnly: false,
    zenMode: false,
    penMode: false,
    zoomWithWheel: false,
    showFrameNames: true,
    interaction: 'idle',
    cursor: 'default',
    canUndo: false,
    canRedo: false,
    contextMenu: null,
    presentation: { active: false, frameIndex: 0, frameIds: [] },
    collaborators: [],
    followingClientId: null,
    sceneVersion: 0,
    searchHighlightIds: [],
    frameOrder: [],
    ...overrides,
  };
}
